// Code generated by sqlc. DO NOT EDIT.

package authors

import (
	"database/sql"
)

type Author struct {
	ID   int64
	Name string
	Bio  sql.NullString
}

type Book struct {
	ID       int64
	Name     string
	AuthorID int64
}
